feat: copy commit hash to clipboard
altsem/gitu pull request #130
Opened 2024-04-12 17:43 UTC by FrancoRav

Add "copy commit hash" feature, bound to "y" by default. Changes default keybinding for show refs to "Y", as suggested in #119 
Closes #119

2024-04-12 19:20 UTC, altsem requested changes
Looks great! Just some minor things.

`cargo fmt --check` seems to be failing, as well as `cargo deny check`. (these are found in the `ci.sh` script).

`BSL-1.0` could be added to the allowed list of licences in [deny.toml](deny.toml)

Perhaps the added changelog (`git cliff --unreleased`) could be a bit more descriptive:
```
### 🚀 Features

- Add copy commit hash feature
```
Something like:
Copy commit hash with "y", move Show refs to "Y"
?

..just to convey that the binding was moved as part of the changelog!

2024-04-12 21:41 UTC, FrancoRav commented
> Looks great! Just some minor things.
> 
> `cargo fmt --check` seems to be failing, as well as `cargo deny check`. (these are found in the `ci.sh` script).
> 
> `BSL-1.0` could be added to the allowed list of licenses in [deny.toml](deny.toml)
> 
> Perhaps the added changelog (`git cliff --unreleased`) could be a bit more descriptive:
> 
> ```
> ### 🚀 Features
> 
> - Add copy commit hash feature
> ```
> 
> Something like: Copy commit hash with "y", move Show refs to "Y" ?
> 
> ..just to convey that the binding was moved as part of the changelog!

I had never used git cliff before. Is there any way to change the changelog message without force pushing to change the commit message?

2024-04-12 22:52 UTC, altsem commented
Hmm perhaps, it'll be finicky though. The release pipeline I've built is all based on these generated messages, there's ways to make exceptions to it. I'm not all too familiar.
But otherwise force-pushing and changing the message is a pretty fix IMO.

2024-04-13 05:28 UTC, FrancoRav commented
I force pushed to reword the commits for the Changelog.
Also, I just noticed the `Clipboard::new()` function fails in the test environment as it can't access any clipboard (the error is `Unknown error while interacting with the clipboard: $DISPLAY variable not set and no value was provided explicitly`). Not sure how to solve this
I was thinking making the Clipboard an `Option<Clipboard>` and leaving None if it errors, but then the feature could not be tested.
Using Option for that is probably necessary anyway, since we need error handling in case it happens in real use, but it still doesn't fix the problem of how to test the feature. Any ideas?

2024-04-13 09:38 UTC, altsem commented
There's not a lot of code, and if we're to test anything, I guess it could be the message?
Seems fine wrapping it in an Option!

2024-04-13 15:45 UTC, FrancoRav commented
> There's not a lot of code, and if we're to test anything, I guess it could be the message? Seems fine wrapping it in an Option!

That's done now. It should pass ci now, and it should be working correctly.
I'm still not sure about the way I am displaying the info and erros in the CmdLog (the methods I added to the State), so if you suggest any changes I can look into that

2024-04-13 16:08 UTC, altsem approved these changes

2024-04-13 16:08 UTC, altsem commented on src/ops/copy_hash.rs
> +            None => state.display_error("Clipboard not available".to_owned()),
I think this would be handled by just returning Err with the message too.
Seems fine either way to me. :+1:

2024-04-13 16:37 UTC, merged