feat: add quit confirmation
altsem/gitu pull request #89
Opened 2024-03-20 07:09 UTC by jondysinger

Implements a prompt if the user initiates a quit from the base screen.

```
? Really quit? (y or n) ›
```

2024-03-21 05:58 UTC, jondysinger commented on src/state.rs
> +                    self.prompt.set(PromptData {
I think it's a good idea to make it configurable. I can see how some may want it and others not. I'll work on the configuration code and add it to this PR.

2024-03-21 06:01 UTC, jondysinger commented on src/state.rs
> +            _ => {}
That's a good point. I'll add that to the PR.

2024-03-21 07:06 UTC, jondysinger commented
I added commits to close the prompt if the user cancels it and for the unit tests. I'm still planning on looking into having the functionality be dependent on configuration.

2024-03-23 03:33 UTC, jondysinger commented
OK I added a config entry and defaulted the behavior to not confirm the quit. I then squashed my commits. It's ready for re-review.

2024-03-23 09:20 UTC, altsem requested changes
Looks good and seems to work! :)
I just had a minor nitpick about the config file comment.

2024-03-23 09:20 UTC, altsem commented on src/default_config.toml
> +
```suggestion
```

I think the option explains itself fairly well!

2024-03-23 09:59 UTC, altsem commented on src/default_config.toml
> +
Bah, since this is just a small thing, I'll go ahead and merge it and change it in master. Hope you don't mind! @jondysinger
:rocket:

2024-03-23 10:01 UTC, altsem approved these changes

2024-03-23 10:11 UTC, merged